services:
    categories.repository.category:
        class: CategoriesBundle\Repository\CategoryRepository
        arguments:
            - "@doctrine.orm.default_entity_manager"

    categories.service.categoryIterator:
        class: CategoriesBundle\Service\Iterator\CategoryIteratorService

    categories.service.categoryTransformer:
        class: CategoriesBundle\Service\Transformer\CategoryTransformer

    categories.service.treeGenerator:
        class: CategoriesBundle\Service\TreeHandler\TreeGeneratorService
        arguments:
            - "@categories.service.categoryTransformer"

    categories.service.completeCategoriesTree:
        class: CategoriesBundle\Service\TreeHandler\CompleteCategoriesTreeService
        public: true
        arguments:
            - "@categories.repository.category"
            - "@categories.service.categoryIterator"
            - "@categories.service.treeGenerator"

    categories.service.visibleChildCategoriesTree:
        class: CategoriesBundle\Service\TreeHandler\VisibleChildCategoriesTreeService
        public: true
        arguments:
            - "@categories.repository.category"
            - "@categories.service.categoryIterator"
            - "@categories.service.treeGenerator"

    categories.service.createCategory:
        class: CategoriesBundle\Service\CreateCategoryService
        public: true
        arguments:
            - "@categories.validator.categoryJsonSchemaValidator"
            - "@categories.repository.category"
            - "@categories.service.categoryTransformer"
            - "@jms_serializer"

    categories.validator.categoryJsonSchemaValidator:
        class: CategoriesBundle\Validator\JsonSchemaValidator
        arguments:
            - "@file_locator"
            - "@@CategoriesBundle/Resources/schema/category.json"

    categories.validator.visibilityJsonSchemaValidator:
        class: CategoriesBundle\Validator\JsonSchemaValidator
        arguments:
            - "@file_locator"
            - "@@CategoriesBundle/Resources/schema/visibility.json"

    categories.service.categoryData:
        class: CategoriesBundle\Service\CategoryDataService
        public: true
        arguments:
            - "@categories.repository.category"

    categories.service.editCategory:
        class: CategoriesBundle\Service\EditCategoryService
        public: true
        arguments:
            - "@categories.validator.visibilityJsonSchemaValidator"
            - "@categories.service.categoryData"
            - "@categories.repository.category"
            - "@jms_serializer"
            - "@categories.service.categoryPatcher"

    categories.service.categoryPatcher:
        class: CategoriesBundle\Service\Patcher\CategoryPatcher

